-- =================
-- DATABASE CREATION
-- =================
CREATE DATABASE LOYALTY_RDS_DB;
USE LOYALTY_RDS_DB;

-- ===============
-- TABLES CREATION
-- ===============
-- #1 CLIENT DB
CREATE TABLE CLIENT(
client_id	INT 		NOT NULL AUTO_INCREMENT,
name		VARCHAR(40) NOT NULL,
-- client_description -- choose between TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT.
PRIMARY KEY(client_id)
);

-- #2 BUSINESS DB
CREATE TABLE BUSINESS(
bus_id		INT 		NOT NULL AUTO_INCREMENT,
name		VARCHAR(40) NOT NULL,
-- bus_description -- choose between TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT.
client_id	INT			NOT NULL,
FOREIGN KEY(client_id) REFERENCES CLIENT(client_id),
PRIMARY KEY(bus_id)
);

-- #3 CUSTOMER DB
CREATE TABLE CUSTOMER(
customer_id		VARCHAR(100) NOT NULL,
client_id		INT			 NOT NULL,
full_name		VARCHAR(50)  NOT NULL,
phone_number	VARCHAR(15), # OPTIONAL: since tourist might not have a valid number. Email is mandatory # CHANGE THIS TO 15 as there can be phone country codes
email			VARCHAR(30)  NOT NULL,
verification	BOOLEAN		 NOT NULL,
address			VARCHAR(50),
member_since 	VARCHAR(10)  NOT NULL,
num_referred	INT,
reward_points	INT,
money_spent     INT,
FOREIGN KEY(client_id) REFERENCES CLIENT(client_id),
PRIMARY KEY(customer_id)
);

-- #4 CARD DB
CREATE TABLE CARD(
card_id			VARCHAR(7)   NOT NULL,
client_id		INT		     NOT NULL,
security_code	INT		     NOT NULL,
status			BOOLEAN      NOT NULL,
customer_id		VARCHAR(100),
card_type		VARCHAR(20)  NOT NULL,
origin			VARCHAR(50),
FOREIGN KEY(customer_id) REFERENCES CUSTOMER(customer_id),
FOREIGN KEY(client_id) REFERENCES CLIENT(client_id),
PRIMARY KEY(card_id)
);

-- #5 PROMO DB
CREATE TABLE PROMO(
promo_id 			  INT 	NOT NULL AUTO_INCREMENT,
client_id			  INT	NOT NULL,
bus_id				  INT,
card_id				  VARCHAR(7),
event_promo		      VARCHAR(59),
gold_promo			  VARCHAR(59),
platinum_promo		  VARCHAR(59),
titanium_promo		  VARCHAR(59),
custom_promo		  VARCHAR(59),
date_valid_from		  DATE	NOT NULL,
date_valid_to		  DATE,        							-- NULL When No expiry date specified
custom_promo_validity ENUM("DATE", "ONE-TIMER", "CLAIMED"), -- DATE implies see data_valid_to for expiry date
FOREIGN KEY(bus_id) REFERENCES BUSINESS(bus_id),
FOREIGN KEY(client_id) REFERENCES CLIENT(client_id),
FOREIGN KEY(card_id) REFERENCES CARD(card_id),
PRIMARY KEY(promo_id)
);

-- #6 SCAN DB
CREATE TABLE SCAN(
scan_id			INT 		 NOT NULL AUTO_INCREMENT,
scan_time		DATETIME	 NOT NULL,
scan_type       ENUM("DIGITAL", "PHYSICAL"), -- To Track if the card was scanned via digital(will have a qr code query param: digital) or physical card
client_id		INT 		 NOT NULL,
bus_id			INT			 NOT NULL,
customer_id		VARCHAR(100) NOT NULL,
card_id			VARCHAR(7)	 NOT NULL,
promo_id		INT			 NOT NULL,
FOREIGN KEY(customer_id) REFERENCES CUSTOMER(customer_id),
FOREIGN KEY(bus_id) REFERENCES BUSINESS(bus_id),
FOREIGN KEY(client_id) REFERENCES CLIENT(client_id),
FOREIGN KEY(promo_id) REFERENCES PROMO(promo_id),
PRIMARY KEY(scan_id)
);

-- =====================
-- DESCRIBING ALL TABLES
-- =====================
USE LOYALTY_RDS_DB;
DESC CLIENT;
DESC BUSINESS;
DESC CUSTOMER;
DESC CARD;
DESC PROMO;
DESC SCAN;

-- ===================
-- DROPPING ALL TABLES
-- =================== 
USE LOYALTY_RDS_DB;
DROP TABLE SCAN;
DROP TABLE PROMO;
DROP TABLE CARD;
DROP TABLE CUSTOMER;
DROP TABLE  BUSINESS;
DROP TABLE CLIENT;

-- =============================================
-- QUERIES(POPULATE DATA TO MATCH DOCUMENTATION)
-- =============================================
INSERT INTO CLIENT VALUES (NULL, "GLOWBAL"); -- AUTO_INCREMENT takes NULL to incremental automatically without query specifying the attribute names(INSERT INTO TABLE(aatribute_1, attribute_2) VALUES(value_1, value_2))
INSERT INTO CLIENT VALUES (NULL, "TABLETOP");
SELECT * FROM CLIENT;

INSERT INTO BUSINESS VALUES (NULL, "BLACK + BLUE VANCOUVER", 1);
INSERT INTO BUSINESS VALUES (NULL, "BLACK + BLUE TORONTO", 1);
INSERT INTO BUSINESS VALUES (NULL, "FIVE SAILS", 1);
INSERT INTO BUSINESS VALUES (NULL, "GLOWBAL", 1);
INSERT INTO BUSINESS VALUES (NULL, "TRATTORIA", 1);
INSERT INTO BUSINESS VALUES (NULL, "ITALIAN KITCHEN", 1);
INSERT INTO BUSINESS VALUES (NULL, "THE ROOF", 1);
INSERT INTO BUSINESS VALUES (NULL, "RILEY'S FISH & GRILL", 1);
INSERT INTO BUSINESS VALUES (NULL, "COAST", 1);
SELECT * FROM BUSINESS;

INSERT INTO CUSTOMER VALUES ("1", 1, "JOHN DOE", 	 "7783337777", "johndoe@icloud.com",  1,  NULL,               '2022-11-20', 0, 0, 0);
INSERT INTO CUSTOMER VALUES ("2", 1, "JOHN DOE", 	 "7783337777", "johndoe@icloud.com",  1, "123 ST. VANCOUVER", '2022-11-21', 0, 0, 0);
INSERT INTO CUSTOMER VALUES ("3", 1, "SERGIO PEREZ", "6045553333", "sergio95@icloud.com", 1,  NULL,                 '2022-11-23', 5, 0, 0);
INSERT INTO CUSTOMER VALUES("b68a77d2-1123-4208-8e86-d7721942142f", 1, "Aryan Arora", "+17787512337", "aryan1998@live.in", 0, NULL, '2023-01-01', 0, 0, 0);
SELECT * FROM CUSTOMER;

INSERT INTO CARD VALUES("00A1000", 1, 333, 1, "b68a77d2-1123-4208-8e86-d7721942142f", "GOLD", "ONLINE SIGNUP");
INSERT INTO CARD VALUES("00AUV6", 1, 001, 1, 1,    "TITANIUM", "REFERRAL");
INSERT INTO CARD VALUES("00AUV9", 1, 063, 1, 2,    "PLATINUM", "FAIRMOUNT HOTEL");
INSERT INTO CARD VALUES("00AUV7", 1, 094, 1, 3,    "GOLD",     "RILEY'S RESTAURANT");
INSERT INTO CARD VALUES("00AUVA", 1, 099, 0, NULL, "EVENT",    "ANNUAL BUSINESS EVENT 2022");
INSERT INTO CARD VALUES("00AUVB", 1, 091, 0, NULL, "EVENT",    "ANNUAL BUSINESS EVENT 2022 Part 2");
INSERT INTO CARD VALUES("00AUVC", 1, 054, 0, NULL, "GOLD",     "LOYALTY TEST FROM HOME");
SELECT * FROM CARD;


INSERT INTO PROMO VALUES(NULL, 1, 1, NULL, NULL, "COMPLEMENTARY_DESSERT", NULL, NULL, NULL, "2023-01-01", "2023-01-31", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 2, NULL, NULL, "15%_OFF_DINE_IN", NULL, NULL, NULL, "2023-01-15", "2023-02-15", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 8, NULL, NULL, "30%_OFF_DRINKS", NULL, NULL, NULL, "2023-01-10", "2023-01-31", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 9, NULL, NULL, "BOGO_DRINKS", NULL, NULL, NULL, "2023-01-01", "2023-01-15", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 5, NULL, NULL, "50%_OFF_WINE_WED", NULL, NULL, NULL, "2023-01-15", "2023-01-31", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 6, NULL, NULL, "$200_DINNER_FOR_$100", NULL, NULL, NULL, "2023-01-01", "2023-02-15", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 3, NULL, NULL, "FREE_DESSERT", NULL, NULL, NULL, "2023-01-15", "2023-02-15", NULL);
INSERT INTO PROMO VALUES(NULL, 1, 4, NULL, NULL, "20%_OFF_LUNCH", NULL, NULL, NULL, "2023-01-01", "2023-01-20", NULL);
SELECT * FROM PROMO;

INSERT INTO PROMO VALUES(NULL, 1, 2, "00A1000", NULL, NULL, NULL, NULL, "20%_OFF_LUNCH", "2023-01-01", "2023-01-20", "DATE");
INSERT INTO PROMO VALUES(NULL, 1, 4, "00A1000", NULL, NULL, NULL, NULL, "50%_OFF_WINE_WED", "2023-01-01", "2023-01-31", "DATE");
INSERT INTO PROMO VALUES(NULL, 1, 6, "00A1000", NULL, NULL, NULL, NULL, "15%_OFF_DINE_IN", "2023-01-01", "2023-02-15", "One-Timer");
INSERT INTO PROMO VALUES(NULL, 1, 8, "00A1000", NULL, NULL, NULL, NULL, "$200_DINNER_FOR_$100", "2023-01-01", NULL, "CLAIMED");
SELECT * FROM PROMO;

INSERT INTO SCAN VALUES(NULL, "2022-11-22 13:00:00", "PHYSICAL", 1, 1, 1, "00AUV6", 1);
INSERT INTO SCAN VALUES(NULL, "2022-11-23 13:01:00", "PHYSICAL", 1, 1, 3, "00AUV7", 1);
INSERT INTO SCAN VALUES(NULL, "2022-11-25 16:00:00", "DIGITAL", 1, 2, 1, "00AUV6", 2);
INSERT INTO SCAN VALUES(NULL, "2023-01-02 16:00:00", "PHYSICAL", 1, 8, "b68a77d2-1123-4208-8e86-d7721942142f", "00A1000", 12);
SELECT * FROM SCAN;

-- ================
-- TETS FOR BACKEND
-- ================
UPDATE CUSTOMER c SET c.num_referred = c.num_referred + 1 WHERE c.customer_id = 4;
SELECT * from CARD c WHERE c.card_type = "GOLD" AND c.status = 0 LIMIT 1;

DELETE FROM CARD c where c.customer_id = 4;
DELETE FROM CUSTOMER c where c.customer_id = 4;
-- ===================
-- QUERIES FOR BACKEND
-- =================== 

-- =========================
-- TESTS FOR LOYALTY WEBSITE
-- =========================
INSERT INTO CARD VALUES("00AUVC", 1, 054, 0, NULL, "GOLD",     "LOYALTY TEST FROM HOME");
DELETE FROM CARD WHERE CARD.card_id = "00AUVC";
SELECT * FROM CARD;
DELETE FROM CUSTOMER WHERE CUSTOMER.customer_id = "1998-03-03";
SELECT * FROM CUSTOMER;
INSERT INTO CARD VALUES("00AUVC", 1, 054, 0, NULL, "GOLD",     "LOYALTY TEST FROM HOME");

SELECT * FROM CARD WHERE CARD.card_id = "00A1UVC";

SELECT * FROM PROMO p, CLIENT c, BUSINESS b WHERE p.card_id is NULL AND p.client_id = c.client_id AND p.bus_id = b.bus_id;

SELECT * FROM PROMO p WHERE p.client_id = 1 AND p.bus_id = 2;


SELECT * FROM PROMO p, CLIENT c, BUSINESS b WHERE p.card_id = '00A1000' AND p.client_id = 1 AND p.bus_id = 2 AND b.bus_id = 2 ORDER BY p.date_valid_from
